parameters:
    calendarApiEndpoints:
        location: '%env(string:CALENDAR_API_FEED_SOURCE_LOCATION_ENDPOINT)%'
        resource: '%env(string:CALENDAR_API_FEED_SOURCE_RESOURCE_ENDPOINT)%'
        event: '%env(string:CALENDAR_API_FEED_SOURCE_EVENT_ENDPOINT)%'
    calendarApiMappings:
        locationId: '%env(string:CALENDAR_API_FEED_SOURCE_MAPPING_LOCATION_ID)%'
        locationDisplayName: '%env(string:CALENDAR_API_FEED_SOURCE_MAPPING_LOCATION_DISPLAY_NAME)%'
        resourceId: '%env(string:CALENDAR_API_FEED_SOURCE_MAPPING_RESOURCE_ID)%'
        resourceLocationId: '%env(string:CALENDAR_API_FEED_SOURCE_MAPPING_RESOURCE_LOCATION_ID)%'
        resourceDisplayName: '%env(string:CALENDAR_API_FEED_SOURCE_MAPPING_RESOURCE_DISPLAY_NAME)%'
        resourceAllowInstantBookings: '%env(string:CALENDAR_API_FEED_SOURCE_MAPPING_RESOURCE_ALLOW_INSTANT_BOOKING)%'
        resourceIncludedInEvents: '%env(string:CALENDAR_API_FEED_SOURCE_MAPPING_RESOURCE_INCLUDED_IN_EVENTS)%'
        eventId: '%env(string:CALENDAR_API_FEED_SOURCE_MAPPING_EVENT_ID)%'
        eventTitle: '%env(string:CALENDAR_API_FEED_SOURCE_MAPPING_EVENT_TITLE)%'
        eventStartTime: '%env(string:CALENDAR_API_FEED_SOURCE_MAPPING_EVENT_START_TIME)%'
        eventEndTime: '%env(string:CALENDAR_API_FEED_SOURCE_MAPPING_EVENT_END_TIME)%'
        eventResourceId: '%env(string:CALENDAR_API_FEED_SOURCE_MAPPING_EVENT_RESOURCE_ID)%'
        eventResourceDisplayName: '%env(string:CALENDAR_API_FEED_SOURCE_MAPPING_EVENT_RESOURCE_DISPLAY_NAME)%'
