---
resources:
  App\Entity\ScreenGroup:
    attributes:
      input: App\Dto\ScreenGroupInput
      output: App\Dto\ScreenGroup
      denormalization_context:
        api_allow_update: true
    itemOperations:
      get:
        path: '/screen-groups/{id}'
        openapi_context:
          description: Retrieves a Screen group resource.
          summary: Retrieve a Screen group resource.
          operationId: get-v1-screen-groups-id
          tags:
            - ScreenGroups
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
              headers: { }

      put:
        path: '/screen-groups/{id}'
        openapi_context:
          description: Update a Screen group resource.
          summary: Update a Screen group resource.
          operationId: put-v1-screen-groups-id
          tags:
            - ScreenGroups
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true

      delete:
        path: '/screen-groups/{id}'
        openapi_context:
          description: Delete a Screen group resource.
          summary: Delete a Screen group resource.
          operationId: delete-v1-screen-groups-id
          tags:
            - ScreenGroups
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true

      putRelateScreen:
        method: PUT
        path: '/screens/{id}/screen-groups'
        controller: App\Controller\ScreenGroupsScreensPutController
        read: false
        deserialize: false
        validate: false
        openapi_context:
          description: Update the collection of ScreenGroups on a Screen.
          summary: Update the collection of ScreenGroups on a Screen.
          operationId: put-v1-screen-groups-screen
          tags:
            - Screens
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
          requestBody:
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: string
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:

      putRelateCampaign:
        method: PUT
        path: '/campaigns/{id}/screen-groups'
        controller: App\Controller\ScreenGroupsCampaignsPutController
        read: false
        deserialize: false
        validate: false
        openapi_context:
          description: Update the collection of ScreenGroups on a campaigns.
          summary: Update the collection of ScreenGroups on a campaigns.
          operationId: put-v1-screen-groups-campaign
          tags:
            - Campaigns
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
          requestBody:
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: string
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:

      deleteRelatedScreen:
        method: DELETE
        path: '/screens/{id}/screen-groups/{screenGroupId}'
        controller: App\Controller\ScreenGroupsScreensDeleteController
        read: false
        deserialize: false
        validate: false
        openapi_context:
          description: Delete a screen groups from a screen.
          summary: Delete a screen groups from a screen
          operationId: delete-v1-screen-group-screen-id
          tags:
            - Screens
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: screenGroupId
              in: path
              required: true

      deleteRelatedCampaign:
        method: DELETE
        path: '/campaigns/{id}/screen-groups/{screenGroupId}'
        controller: App\Controller\ScreenGroupsCampaignsDeleteController
        read: false
        deserialize: false
        validate: false
        openapi_context:
          description: Delete a screen groups from a campaign.
          summary: Delete a screen groups from a campaign
          operationId: delete-v1-screen-group-campaign-id
          tags:
            - Campaigns
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: screenGroupId
              in: path
              required: true

    collectionOperations:
      get:
        filters: ['entity.search_filter', 'entity.order_filter']
        path: '/screen-groups'
        openapi_context:
          description: Retrieve a collection of Screen group resources.
          summary: Retrieves a collection of Screen group resources.
          tags:
            - ScreenGroups
          operationId: get-v1-screen-groups
          parameters:
            - schema:
                type: integer
                minimum: 0
                format: int32
                default: 1
              in: query
              name: page
            - schema:
                type: string
                default: '10'
              in: query
              name: itemsPerPage
              description: The number of items per page
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
              headers: { }

      getBaseOnRegion:
        method: GET
        filters: ['entity.order_filter']
        path: '/screens/{id}/screen-groups'
        controller: App\Controller\ScreenGroupsScreensGetController
        read: false
        openapi_context:
          operationId: get-v1-screen-id-screen-groups
          description: Retrieve ScreenGroups collection base on screen id.
          summary: Retrieve ScreenGroups collection base on screen id.
          tags:
            - Screens
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
            - schema:
                type: integer
                minimum: 0
                format: int32
                default: 1
              in: query
              name: page
              required: true
            - schema:
                type: string
                default: '10'
              in: query
              name: itemsPerPage
              description: The number of items per page

      getCampaginsBaseOnRegion:
        method: GET
        filters: ['entity.order_filter']
        path: '/campaigns/{id}/screen-groups'
        controller: App\Controller\ScreenGroupsCampaignsGetController
        read: false
        openapi_context:
          operationId: get-v1-campaign-id-screen-groups
          description: Retrieve ScreenGroups collection based on campaign id.
          summary: Retrieve ScreenGroups collection based on campaign id.
          tags:
            - Campaigns
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
            - schema:
                type: integer
                minimum: 0
                format: int32
                default: 1
              in: query
              name: page
              required: true
            - schema:
                type: string
                default: '10'
              in: query
              name: itemsPerPage
              description: The number of items per page

      post:
        path: '/screen-groups'
        openapi_context:
          description: Create Screen group resources.
          summary: Create Screen group resources.
          operationId: post-v1-screen-groups
          tags:
            - ScreenGroups
